<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TMS_seeder extends Seeder
{
    public function run(): void
    {
        $this->insertTrainingPrograms();
    }

    private function insertTrainingPrograms(): void
    {
        $trainings = [
            [
                'program_name' => 'Training 1',
                'provider' => 'Internal HR',
                'duration' => '1 Day',
                'target_skills' => 'Leadership, Strategic Thinking, Communication',
                'status' => 'Active',
                'feedback_score' => 48,
                'description' => 'This is just a test description for Training 1.',
                'objectives' => 'Test Objectives',
                'trainer' => 'Trainer A',
                'prerequisites' => 'Test Prerequisites',
                'start_date' => Carbon::now()->addDays(14)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(16)->format('Y-m-d H:i:s'),
                'max_participants' => 15,
                'location' => 'Conference Room A',
                'training_type' => 'In-Person',
                'difficulty' => 'Advanced',
                'format' => 'Workshop',
                'topic' => 'Leadership',
                'rating' => 4.8,
                'enrolled_count' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'program_name' => 'Training 2',
                'provider' => 'External Vendor',
                'duration' => '3 Days',
                'target_skills' => 'Project Management, Time Management',
                'status' => 'Active',
                'feedback_score' => 45,
                'description' => 'This is just a test description for Training 2.',
                'objectives' => 'Test Objectives',
                'trainer' => 'Trainer B',
                'prerequisites' => 'Test Prerequisites',
                'start_date' => Carbon::now()->addDays(21)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(24)->format('Y-m-d H:i:s'),
                'max_participants' => 20,
                'location' => 'Online',
                'training_type' => 'In-Person',
                'difficulty' => 'Intermediate',
                'format' => 'Seminar',
                'topic' => 'Project Management',
                'rating' => 4.5,
                'enrolled_count' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'program_name' => 'Training 3',
                'provider' => 'Internal HR',
                'duration' => '2 Days',
                'target_skills' => 'Customer Service, Problem Solving',
                'status' => 'Planned',
                'feedback_score' => null,
                'description' => 'This is just a test description for Training 3.',
                'objectives' => 'Test Objectives',
                'trainer' => 'Trainer C',
                'prerequisites' => 'Test Prerequisites',
                'start_date' => Carbon::now()->addDays(30)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(32)->format('Y-m-d H:i:s'),
                'max_participants' => 10,
                'location' => 'Conference Room B',
                'training_type' => 'In-Person',
                'difficulty' => 'Beginner',
                'format' => 'Workshop',
                'topic' => 'Customer Service',
                'rating' => 0.00,
                'enrolled_count' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'program_name' => 'Training 4',
                'provider' => 'External Vendor',
                'duration' => '4 Days',
                'target_skills' => 'Data Analysis, Excel Skills',
                'status' => 'Planned',
                'feedback_score' => null,
                'description' => 'This is just a test description for Training 4.',
                'objectives' => 'Test Objectives',
                'trainer' => 'Trainer D',
                'prerequisites' => 'Test Prerequisites',
                'start_date' => Carbon::now()->addDays(40)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(44)->format('Y-m-d H:i:s'),
                'max_participants' => 25,
                'location' => 'Online',
                'training_type' => 'In-Person',
                'difficulty' => 'Intermediate',
                'format' => 'Seminar',
                'topic' => 'Data Analysis',
                'rating' => 0.00,
                'enrolled_count' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'program_name' => 'Training 5',
                'provider' => 'Internal HR',
                'duration' => '1 Day',
                'target_skills' => 'Time Management, Productivity',
                'status' => 'Active',
                'feedback_score' => 50,
                'description' => 'This is just a test description for Training 5.',
                'objectives' => 'Test Objectives',
                'trainer' => 'Trainer E',
                'prerequisites' => 'Test Prerequisites',
                'start_date' => Carbon::now()->addDays(10)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(11)->format('Y-m-d H:i:s'),
                'max_participants' => 30,
                'location' => 'Conference Room C',
                'training_type' => 'In-Person',
                'difficulty' => 'Beginner',
                'format' => 'Workshop',
                'topic' => 'Productivity',
                'rating' => 5.0,
                'enrolled_count' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'program_name' => 'Training 6',
                'provider' => 'External Vendor',
                'duration' => '2 Days',
                'target_skills' => 'Conflict Resolution, Negotiation',
                'status' => 'Planned',
                'feedback_score' => null,
                'description' => 'This is just a test description for Training 6.',
                'objectives' => 'Test Objectives',
                'trainer' => 'Trainer F',
                'prerequisites' => 'Test Prerequisites',
                'start_date' => Carbon::now()->addDays(50)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(52)->format('Y-m-d H:i:s'),
                'max_participants' => 20,
                'location' => 'Online',
                'training_type' => 'In-Person',
                'difficulty' => 'Advanced',
                'format' => 'Seminar',
                'topic' => 'Negotiation',
                'rating' => 0.00,
                'enrolled_count' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'program_name' => 'Training 7',
                'provider' => 'Internal HR',
                'duration' => '3 Days',
                'target_skills' => 'Emotional Intelligence, Teamwork',
                'status' => 'Active',
                'feedback_score' => 47,
                'description' => 'This is just a test description for Training 7.',
                'objectives' => 'Test Objectives',
                'trainer' => 'Trainer G',
                'prerequisites' => 'Test Prerequisites',
                'start_date' => Carbon::now()->addDays(5)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(8)->format('Y-m-d H:i:s'),
                'max_participants' => 18,
                'location' => 'Conference Room D',
                'training_type' => 'In-Person',
                'difficulty' => 'Intermediate',
                'format' => 'Workshop',
                'topic' => 'Teamwork',
                'rating' => 4.7,
                'enrolled_count' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'program_name' => 'Training 8',
                'provider' => 'External Vendor',
                'duration' => '1 Day',
                'target_skills' => 'Creative Thinking, Innovation',
                'status' => 'Planned',
                'feedback_score' => null,
                'description' => 'This is just a test description for Training 8.',
                'objectives' => 'Test Objectives',
                'trainer' => 'Trainer H',
                'prerequisites' => 'Test Prerequisites',
                'start_date' => Carbon::now()->addDays(60)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(61)->format('Y-m-d H:i:s'),
                'max_participants' => 25,
                'location' => 'Online',
                'training_type' => 'In-Person',
                'difficulty' => 'Beginner',
                'format' => 'Seminar',
                'topic' => 'Innovation',
                'rating' => 0.00,
                'enrolled_count' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'program_name' => 'Training 9',
                'provider' => 'Internal HR',
                'duration' => '2 Days',
                'target_skills' => 'Stress Management, Work-Life Balance',
                'status' => 'Active',
                'feedback_score' => 49,
                'description' => 'This is just a test description for Training 9.',
                'objectives' => 'Test Objectives',
                'trainer' => 'Trainer I',
                'prerequisites' => 'Test Prerequisites',
                'start_date' => Carbon::now()->addDays(12)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(14)->format('Y-m-d H:i:s'),
                'max_participants' => 30,
                'location' => 'Conference Room E',
                'training_type' => 'In-Person',
                'difficulty' => 'Beginner',
                'format' => 'Workshop',
                'topic' => 'Work-Life Balance',
                'rating' => 4.9,
                'enrolled_count' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'program_name' => 'Training 10',
                'provider' => 'External Vendor',
                'duration' => '3 Days',
                'target_skills' => 'Digital Marketing, SEO',
                'status' => 'Planned',
                'feedback_score' => null,
                'description' => 'This is just a test description for Training 10.',
                'objectives' => 'Test Objectives',
                'trainer' => 'Trainer J',
                'prerequisites' => 'Test Prerequisites',
                'start_date' => Carbon::now()->addDays(70)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(73)->format('Y-m-d H:i:s'),
                'max_participants' => 20,
                'location' => 'Online',
                'training_type' => 'In-Person',
                'difficulty' => 'Intermediate',
                'format' => 'Seminar',
                'topic' => 'Digital Marketing',
                'rating' => 0.00,
                'enrolled_count' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
        DB::table('training_management')->insert($trainings);
    }
}